# Publish GitHub Pages

trigger:
  branches:
    include:
      - master
      - refs/tags/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeToolVersion: '12.5.0'
  outFile: 'target'

steps:
- script: |
    mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
    chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    pushd target > /dev/null
    git clone git@github.com:capra314cabra/blue-spoon.git .
    git checkout gh-pages
    popd > /dev/null
  displayName: 'Setup git repo'
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')

- task: NodeTool@0
  inputs:
    versionSpec: $(nodeToolVersion)
  displayName: 'Install node js'

- script: npm install -g typescript
  displayName: 'Install typescript compiler'

- script: tsc
  displayName: 'Compile typescript codes'

- script: |
    pushd tools > /dev/null
    chmod +x bake.sh
    popd > /dev/null
    ./tools/bake.sh
  displayName: 'Bake files'

- script: |
    pushd target > /dev/null
    pwd
    git config --local user.name "Bluespoon Bot"
    git config --local user.email "bluespoonbot@capra314cabra.github.io"
    git add .
    git commit -m "Auto Publishing GitHub Pages From '$(Build.SourceBranch)'"
    popd > /dev/null
  displayName: 'Commit compiled changes'
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
    

- task: DownloadSecureFile@1
  inputs:
    secureFile: bs_github_rsa
  displayName: 'Get the deploy key'
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')

- script: |
    pushd target > /dev/null
    git push origin gh-pages
    popd > /dev/null
  displayName: 'Publish all'
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
